version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-flask-container
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
      - ./logs:/app/logs
    environment:
      FLASK_ENV: production
      TOKENIZERS_PARALLELISM: "false"
    depends_on:
      - db
      - chroma
    networks:
      - net

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: buc_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma-container
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "8001:8000"
    networks:
      - net

volumes:
  pgdata:
    driver: local
  index_data:
    driver: local

networks:
  net:
    driver: bridge
