services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-flask-container
    ports:
      - "8000:8000"  # App runs on 8000, externally accessible
    volumes:
      - ./:/app/      # Mounts local dir to /app/, preserving src/app.py
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=production
      - TOKENIZERS_PARALLELISM=false
      - DATABASE_URL=sqlite:///BUCDB/chroma.sqlite3  # Use the BUCDB database
    networks:
      - net

volumes:
  index_data:
    driver: local

networks:
  net:
    driver: bridge