services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-flask-container
    ports:
      - "8000:8000"  # App runs on 8000, externally accessible
    volumes:
      - ./:/app/      # Mounts local dir to /app/, preserving src/app.py
      - ./logs:/app/logs  # Redundant but kept for explicitness
      - ./.env:/app/.env  # Redundant but kept for explicitness
    environment:
      - FLASK_ENV=production
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      - chroma
    networks:
      - net
 # Override CMD to ensure it runs from src/

  chroma:
    image: ghcr.io/chroma-core/chroma:latest # Use the working custom image or build and use the local
    volumes:
      - index_data:/chroma/.chroma/index  # Align with the working setup
    ports:
      - "8001:8000"  # Chroma runs on 8000 internally, mapped to 8001 externally
    networks:
      - net

volumes:
  index_data:
    driver: local

networks:
  net:
    driver: bridge